baseURL = 'https://csunibo.github.io/wiki/'
languageCode = 'it-IT'
title = 'Wiki'
theme = "hugo-theme-relearn"

[module]
[[module.imports]]
  path = 'github.com/McShelby/hugo-theme-relearn'

[outputs]
home = [ "HTML", "RSS", "SEARCH"]
